
import { City, Genre, Event, CityInfo } from './types';

export const CITIES: CityInfo[] = [
    { name: City.Nairobi, latitude: -1.2921, longitude: 36.8219 },
    { name: City.Kisumu, latitude: -0.0917, longitude: 34.7680 },
    { name: City.Mombasa, latitude: -4.0435, longitude: 39.6682 },
    { name: City.Nakuru, latitude: -0.3031, longitude: 36.0800 },
    { name: City.Kampala, latitude: 0.3476, longitude: 32.5825 },
    { name: City.DarEsSalaam, latitude: -6.7924, longitude: 39.2083 },
];

export const INTERESTS: Genre[] = [
    Genre.Mugithi,
    Genre.HipHop,
    Genre.Outdoor,
    Genre.WineBeer,
    Genre.Ohangla,
    Genre.LiveBand,
    Genre.CarShow,
    Genre.Cultural,
];

export const MOCK_EVENTS: Event[] = [
    {
        id: 1,
        title: 'Mugithi Night with Samidoh',
        flyerImageUrl: 'https://picsum.photos/seed/event1/600/800',
        date: new Date(new Date().setDate(new Date().getDate() + 1)),
        venue: 'Kasarani Stadium, Nairobi',
        cost: 'KES 1000',
        city: City.Nairobi,
        genre: Genre.Mugithi,
        description: 'Join the king of Mugithi for a night of vibrant music and dance. An unforgettable experience awaits you with live performances of all his greatest hits.',
        latitude: -1.223,
        longitude: 36.887,
        isPromoted: false,
    },
    {
        id: 2,
        title: 'Nairobi Hip Hop Fest',
        flyerImageUrl: 'https://picsum.photos/seed/event2/600/800',
        date: new Date(new Date().setDate(new Date().getDate() + 2)),
        venue: 'The Alchemist, Westlands',
        cost: 'KES 1500',
        city: City.Nairobi,
        genre: Genre.HipHop,
        description: 'The biggest hip hop festival in the city is back! Featuring top local and international artists. Get ready for electrifying performances and non-stop beats.',
        latitude: -1.265,
        longitude: 36.804,
        isPromoted: true,
    },
    {
        id: 3,
        title: 'Kisumu Ohangla Extravaganza',
        flyerImageUrl: 'https://picsum.photos/seed/event3/600/800',
        date: new Date(new Date().setDate(new Date().getDate() + 8)),
        venue: 'Acacia Premier Hotel',
        cost: 'KES 800',
        city: City.Kisumu,
        genre: Genre.Ohangla,
        description: 'Experience the best of Ohangla music by the lake. A cultural celebration with food, music, and dance.',
        latitude: -0.103,
        longitude: 34.752,
        isPromoted: false,
    },
    {
        id: 4,
        title: 'Mombasa Beach Festival',
        flyerImageUrl: 'https://picsum.photos/seed/event4/600/800',
        date: new Date(new Date().setDate(new Date().getDate() + 3)),
        venue: 'Pirates Beach, Mombasa',
        cost: 'Free Entry',
        city: City.Mombasa,
        genre: Genre.Outdoor,
        description: 'Sun, sand, and sound! A two-day festival featuring live bands, DJs, food stalls, and beach games. Fun for the whole family.',
        latitude: -4.001,
        longitude: 39.721,
        isPromoted: false,
    },
    {
        id: 5,
        title: 'Rooftop Wine & Beer Tasting',
        flyerImageUrl: 'https://picsum.photos/seed/event5/600/800',
        date: new Date(),
        venue: 'K1 Klub House, Nairobi',
        cost: 'KES 2500',
        city: City.Nairobi,
        genre: Genre.WineBeer,
        description: 'An exclusive evening of wine and craft beer tasting with panoramic city views. Mingle with connoisseurs and enjoy gourmet pairings.',
        latitude: -1.272,
        longitude: 36.809,
        isPromoted: false,
    },
    {
        id: 6,
        title: 'Vintage Car Show',
        flyerImageUrl: 'https://picsum.photos/seed/event6/600/800',
        date: new Date(new Date().setDate(new Date().getDate() + 9)),
        venue: 'Uhuru Gardens',
        cost: 'KES 500',
        city: City.Nairobi,
        genre: Genre.CarShow,
        description: 'A display of the finest classic and vintage cars in East Africa. A perfect day out for auto enthusiasts and families.',
        latitude: -1.325,
        longitude: 36.811,
        isPromoted: false,
    },
    {
        id: 7,
        title: 'Sauti Sol Live in Concert',
        flyerImageUrl: 'https://picsum.photos/seed/event7/600/800',
        date: new Date(new Date().setDate(new Date().getDate() + 4)),
        venue: 'Carnivore Grounds',
        cost: 'KES 3000',
        city: City.Nairobi,
        genre: Genre.LiveBand,
        description: 'Catch the legendary Sauti Sol live on stage for their Midnight Train tour. A night of soulful music and incredible performances.',
        latitude: -1.325,
        longitude: 36.804,
        isPromoted: false,
    },
     {
        id: 8,
        title: 'Cultural Night Mombasa',
        flyerImageUrl: 'https://picsum.photos/seed/event8/600/800',
        date: new Date(new Date().setDate(new Date().getDate() + 15)),
        venue: 'Fort Jesus, Mombasa',
        cost: 'KES 700',
        city: City.Mombasa,
        genre: Genre.Cultural,
        description: 'Immerse yourself in the rich Swahili culture with traditional music, dance, and cuisine under the stars at the historic Fort Jesus.',
        latitude: -4.062,
        longitude: 39.678,
        isPromoted: true,
    },
    {
        id: 9,
        title: 'Lakeside Live Band Festival',
        flyerImageUrl: 'https://picsum.photos/seed/event9/600/800',
        date: new Date(new Date().setDate(new Date().getDate() + 5)),
        venue: 'Dunga Hill Camp, Kisumu',
        cost: 'KES 1200',
        city: City.Kisumu,
        genre: Genre.LiveBand,
        description: 'Enjoy a weekend of amazing live music from Kenya\'s top bands, right by the beautiful shores of Lake Victoria. Good vibes only!',
        latitude: -0.119,
        longitude: 34.740,
        isPromoted: true,
    },
    {
        id: 10,
        title: 'Kampala Night Life Fest',
        flyerImageUrl: 'https://picsum.photos/seed/event10/600/800',
        date: new Date(new Date().setDate(new Date().getDate() + 6)),
        venue: 'Lugogo Cricket Oval, Kampala',
        cost: 'UGX 50000',
        city: City.Kampala,
        genre: Genre.LiveBand,
        description: 'A celebration of Ugandan music and culture with performances from the nation\'s biggest stars. Food, drinks, and music all night long.',
        latitude: 0.329,
        longitude: 32.602,
        isPromoted: false,
    },
    {
        id: 11,
        title: 'Bongo Flava Beach Party',
        flyerImageUrl: 'https://picsum.photos/seed/event11/600/800',
        date: new Date(new Date().setDate(new Date().getDate() + 12)),
        venue: 'Coco Beach, Dar es Salaam',
        cost: 'TZS 20000',
        city: City.DarEsSalaam,
        genre: Genre.Outdoor,
        description: 'Dance to the latest Bongo Flava hits right by the ocean. The biggest beach party of the year with top DJs and surprise artists.',
        latitude: -6.762,
        longitude: 39.289,
        isPromoted: true,
    },
    {
        id: 12,
        title: 'Rift Valley Cultural Festival',
        flyerImageUrl: 'https://picsum.photos/seed/event12/600/800',
        date: new Date(new Date().setDate(new Date().getDate() + 20)),
        venue: 'Nakuru Athletics Club',
        cost: 'KES 500',
        city: City.Nakuru,
        genre: Genre.Cultural,
        description: 'Experience the diverse cultures of the Rift Valley with traditional food, music, and art. A family-friendly event for everyone.',
        latitude: -0.283,
        longitude: 36.067,
        isPromoted: false,
    }
];
